name: discordbot
secrets:
  DISCORD_TOKEN:
    required: true
  REDIS_ENDPOINT:
    required: true
  REDIS_PASSWORD:
    required: true
services:
  discordbot:
    environment:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      REDIS_ENDPOINT: ${{ secrets.REDIS_ENDPOINT }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
    build:
      context: ../.
      dockerfile: DiscordBot.Dockerfile
    reserved_name: discordbot
  event-processor:
    environment:
      REDIS_ENDPOINT: ${{ secrets.REDIS_ENDPOINT }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
    build:
      context: ../.
      dockerfile: EventProcessor.Dockerfile
    reserved_name: event-processor
  timed-actions-worker:
    environment:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      REDIS_ENDPOINT: ${{ secrets.REDIS_ENDPOINT }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
    build:
      context: ../.
      dockerfile: TimedActionsWorker.Dockerfile
    reserved_name: timed-actions-worker
