version: '3.4' 
name: discord-bot

services:
  discordbot:
    image: discordbot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - REDIS_ENDPOINT=${REDIS_ENDPOINT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    build:
      context: ../.
      dockerfile: Dockerfile