name: Architect master Branch Deployment

on:
  push:
    branches:
      - master

env:
  ARCHITECT_GENERATED: true
  ARCHITECT_BRANCH: true
  COMPONENT_FILE_PATH: deployment/architect.yml
  ARCHITECT_ACCOUNT: taigadev-io
  COMPONENT_NAME: arch-io-cluster
  ENVIRONMENT_NAME: discord-bot-github
  BRANCH_NAME: master

jobs:
  architect_on_push_deployments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - uses: crazy-max/ghaction-github-runtime@v2 # Exports internal envs for Github Actions. Required for register caching to work.
      - name: Install Architect CLI
        run: npm install -g @architect-io/cli
      - name: Login to Architect Cloud
        run: architect login -e "${{ secrets.ARCHITECT_EMAIL }}" -p "${{ secrets.ARCHITECT_PASSWORD }}"
      - name: Register component w/ Architect
        run: architect register ${{ env.COMPONENT_FILE_PATH }} -t latest
      - name: Deploy component
        run: architect deploy --auto-approve -e ${{ env.ENVIRONMENT_NAME }} ${{ env.COMPONENT_NAME }}:latest
