name: Build & Push images to dockerhub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-timed-actions-worker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Build TimedActionsWorker
      run: dotnet build src/TimedActionsWorker/TimedActionsWorker.csproj --configuration Release
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push TimedActionsWorker
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        file: TimedActionsWorker.Dockerfile
        platforms: linux/arm64v8
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/timed-actions-worker:latest
        github-token: ${{ github.token }} 
  build-event-processor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Build EventProcessor
      run: dotnet build src/EventProcessor/EventProcessor.csproj --configuration Release
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push EventProcessor
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        file: EventProcessor.Dockerfile
        platforms: linux/arm64v8
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/event-processor:latest         # GitHub Token used to authenticate against a repository for Git context
        github-token: ${{ github.token }} # optional, default is ${{ github.token }}
  build-discordbot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Build DiscordBot
      run: dotnet build src/DiscordBot/DiscordBot.csproj --configuration Release
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push DiscordBot
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        file: DiscordBot.Dockerfile
        platforms: linux/arm64v8
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/discordbot:latest         # GitHub Token used to authenticate against a repository for Git context
        github-token: ${{ github.token }} # optional, default is ${{ github.token }}
    
