name: Build & Push images to dockerhub

on:
  push:
    branches: [ master ]

jobs:
  docker-remote-swarm:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Docker Swarm
      uses: wshihadeh/docker-deployment-action@v2
      with:
        deployment_mode: docker-compose
        remote_docker_host: ${{ secrets.REMOTE_HOST }}
        remote_docker_port: 23
        ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        ssh_private_key: ${{ secrets.REMOTE_SSH_PRIVATE_KEY }}
        stack_file_name: /deployment/docker-compose.yml
        pull_images_first: false
        args: docker
  build-timed-actions-worker:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Build TimedActionsWorker
      run: dotnet build src/TimedActionsWorker/TimedActionsWorker.csproj --configuration Release
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push TimedActionsWorker Image
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        no-cache: true
        file: TimedActionsWorker.Dockerfile
        platforms: linux/arm64
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/timed-actions-worker:latest
        github-token: ${{ github.token }} 
  build-event-processor:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Build EventProcessor
      run: dotnet build src/EventProcessor/EventProcessor.csproj --configuration Release
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push EventProcessor Image
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        no-cache: true
        file: EventProcessor.Dockerfile
        platforms: linux/arm64/v8
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/event-processor:latest         # GitHub Token used to authenticate against a repository for Git context
        github-token: ${{ github.token }} # optional, default is ${{ github.token }}
  build-discordbot:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Build DiscordBot
      run: dotnet build src/DiscordBot/DiscordBot.csproj --configuration Release
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push DiscordBot Image
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        no-cache: true
        file: DiscordBot.Dockerfile
        platforms: darwin
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/discordbot:latest         # GitHub Token used to authenticate against a repository for Git context
        github-token: ${{ github.token }} # optional, default is ${{ github.token }}
    
