name: Build & Push images to dockerhub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Build TimedActionsWorker
      run: dotnet build src/TimedActionsWorker/TimedActionsWorker.csproj --configuration Release
    - name: Build EventProcessor
      run: dotnet build src/EventProcessor/EventProcessor.csproj --configuration Release
    - name: Build DiscordBot
      run: dotnet build src/DiscordBot/DiscordBot.csproj --configuration Release
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push TimedActionsWorker
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        file: TimedActionsWorker.Dockerfile
        platform: linux/arm64v8
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/timed-action-sworker:latest         # GitHub Token used to authenticate against a repository for Git context
        github-token: ${{ github.token }} # optional, default is ${{ github.token }}
    - name: Build and push EventProcessor
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        file: EventProcessor.Dockerfile
        platform: linux/arm64v8
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/event-processor:latest         # GitHub Token used to authenticate against a repository for Git context
        github-token: ${{ github.token }} # optional, default is ${{ github.token }}
    - name: Build and push DiscordBot
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        file: DiscordBot.Dockerfile
        platform: linux/arm64v8
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/discordbot:latest         # GitHub Token used to authenticate against a repository for Git context
        github-token: ${{ github.token }} # optional, default is ${{ github.token }}
    
